[RELAY]
light.gpio.pin=17
light.two.gpio.pin=27
exhaust.gpio.pin=5
humidifier.gpio.pin=22
fan.gpio.pin=26
inline.fan.gpio.pin=6
valve.gpio.pin=16
pump.gpio.pin=13

[DHT11]
dht11.gpio.pin=18
dht11.retries=10
dht11.sleep.time=2.0

[SEN0205]
sen0205.max.gpio.pin=24
sen0205.min.gpio.pin=23

[PI]
chip=/dev/gpiochip0
