[RELAY]
light.gpio.pin=19
exhaust.gpio.pin=26
humidifier.gpio.pin=13
fan.gpio.pin=6

[DHT11]
dht11.gpio.pin=18
dht11.retries=10
dht11.sleep.time=2.0

[SEN0205]
sen0205.max.gpio.pin=5
sen0205.min.gpio.pin=6

[PI]
chip=/dev/gpiochip0
